name: "Code linter check"

on: [push, pull_request]

jobs:
  main:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install flit
      run: |
        python -m pip install --upgrade pip
        python -m pip install 'flit>=3.8.0'

    - name: Install project dependencies
      run: |
        flit install --deps develop

    - name: Run isort
      run: |
        isort --check src/

    - name: Run black
      run: |
        black --check src/

    - name: Run pylint
      run: |
        pylint src/ || true